-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE SEQUENCE sq_dbrole;
CREATE SEQUENCE sq_dbtableaccess;
CREATE SEQUENCE sq_dbuser;
CREATE SEQUENCE sq_dbuserrole;
CREATE SEQUENCE sq_dbentity;



CREATE TABLE IF NOT EXISTS public.dbrole
(
    id integer NOT NULL DEFAULT nextval('sq_dbrole'),
    name character varying,
    description text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dbtableaccess
(
    id integer NOT NULL DEFAULT nextval('sq_dbtableaccess'),
    tableaccess character varying(255),
    dbrole_id integer,
    userrolerestrictions character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dbuser
(
    id integer NOT NULL DEFAULT nextval('sq_dbuser'),
    login character varying(255) UNIQUE,
    password character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dbuserrole
(
    id integer NOT NULL DEFAULT nextval('sq_dbuserrole'),
    dbuser_id integer,
    dbentity_id integer,
    dbrole_id integer,
    startdate timestamp without time zone,
    enddate timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dbentity
(
    id integer NOT NULL DEFAULT nextval('sq_dbentity'),
    type character varying(255),
    parent_id bigint,
    description text,
    PRIMARY KEY (id)
);




END;