version: '3.1'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
        - sqldb
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
  traefik:
    image: traefik:v2.10.4
    container_name: traefik
    restart: unless-stopped
    networks:
      - sqldb
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
    volumes:
      - ./html:/opt/html
      - /var/run/docker.sock:/var/run/docker.sock
    
  sqldb-gateway:
    image: irtse/sqldb-gateway:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - sqldb
    ports: 
      - 8081:8080 # Expose Traefik on port 8000    
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sqldb.entrypoints=web"
        - "traefik.http.routers.sqldb.rule=PathPrefix(`/v1`)"
        - "traefik.http.services.sqldb.loadbalancer.server.port=8080"
networks:
  sqldb:
    external: true

volumes:
  redis-data:
    driver: local