version: '3.1'

services:
  sqldb-ws:
    image: irtse/sqldb-ws:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - sqldb
    ports: 
      - 8081:8080
    volumes:
      - ./files:/mnt/files
      - ./html:/opt/html
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sqldb.entrypoints=web"
        - "traefik.http.routers.sqldb.rule=PathPrefix(`/v1`)"
        - "traefik.http.services.sqldb.loadbalancer.server.port=8080"
    environment:
      LDAP_ADDR: ${LDAP_ADDR:-ldap://irt00v001.irt-aese.local:389}
      LDAP_USR: ${LDAP_USR:-CN=read only,OU=Utilisateurs,OU=YZ - Technique,OU=AD - IRT-AESE,DC=IRT-AESE,DC=local}
      LDAP_OU: ${LDAP_USR:-OU=AD - IRT-AESE,DC=IRT-AESE,DC=local}
      LDAP_PWD: ${LDAP_PWD:-IRT@2015}
      SMTP_HOST: ${SMTP_HOST:-mail.irt-saintexupery.com}
      SMTP_PORT: ${SMTP_PORT:-25}
      SUPERADMIN_NAME: ${SUPERADMIN_NAME:-root}
      SUPERADMIN_EMAIL: ${SUPERADMIN_EMAIL:-pro.morgane.roques@gmail.com}
      SUPERADMIN_PASSWORD: ${SUPERADMIN_PASSWORD:-admin}
      AUTH_MODE: ${AUTH_MODE:-ldap}
      DBDRIVER : ${DBDRIVER:-postgres}
      DBHOST : ${DBHOST:-sqldb-ws-pg}
      DBPORT : ${DBPORT:-5432}
      DBUSER : ${DBUSER:-test}
      DBPWD : ${DBPWD:-test}
      DBNAME: ${DBNAME:-test}
      DBSSL: ${DBSSL:-disable}
      HOST: ${HOST:-http://capitalisation.irt-aese.local}
networks:
  sqldb:
    external: true