version: '3.1'

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    # if you are running as root then set it to 0
    # else find the right id with the id -u command
    user: '0'
    networks:
      - sqldb
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
    ports:
      - '8080:3000'
    # adding the mount volume point which we create earlier
    volumes:
      - '$PWD/data:/var/lib/grafana'
      - ./custom.js:/etc/grafana/custom.js
      - ./custom-entrypoint.sh:/etc/grafana/custom-entrypoint.sh
    entrypoint: ["/etc/grafana/custom-entrypoint.sh"]
  pg:
    image: postgres:alpine
    container_name: ${DBHOST:-sqldb-ws-pg}
    restart: always
    volumes:
      - ./db/autoload:/docker-entrypoint-initdb.d
      - /opt/data/containers/sqldb/pgdata:/var/lib/postgresql/data
    networks:
      - sqldb
    environment:
      POSTGRES_DB: ${DBNAME:-test}
      POSTGRES_USER: ${DBUSER:-test}
      POSTGRES_PASSWORD: ${DBPWD:-test}
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    networks:
      - sqldb
    ports:
      - 8443:8080
networks:
  sqldb:
    external: true