version: '3.1'

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    # if you are running as root then set it to 0
    # else find the right id with the id -u command
    user: '0'
    networks:
      - sqldb
    ports:
      - '3000:3000'
    # adding the mount volume point which we create earlier
    volumes:
      - '$PWD/data:/var/lib/grafana'
  pg:
    image: postgres:alpine
    container_name: ${DBHOST:-sqldb-ws-pg}
    restart: always
    volumes:
      - ./db/autoload:/docker-entrypoint-initdb.d
      - /opt/data/containers/sqldb/pgdata:/var/lib/postgresql/data
    networks:
      - sqldb
    environment:
      POSTGRES_DB: ${DBNAME:-test}
      POSTGRES_USER: ${DBUSER:-test}
      POSTGRES_PASSWORD: ${DBPWD:-test}
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    networks:
      - sqldb
    ports:
      - 8443:8080
networks:
  sqldb:
    external: true