version: '3.1'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
        - sqldb
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
  sqldb-gateway:
    image: irtse/sqldb-gateway:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - sqldb
    ports: 
      - 8080:80
networks:
  sqldb:
    external: true

volumes:
  redis-data:
    driver: local