basePath: /v1
definitions:
  json:
    title: json
    type: object
info:
  contact:
    email: yves.cerezal@irt-saintexupery.com
  description: |
    Generic database access API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.irt-saintexupery.com/
  title: SqlDB WS API
  version: 1.0.0
paths:
  "":
    get:
      description: |-
        Main Datas
        <br>
      operationId: MainController.Main
      parameters:
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - ""
  /login:
    post:
      description: |-
        Login Datas
        <br>
      operationId: AuthController.Login
      parameters:
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      - description: 'Request body '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/json'
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - ""
  /logout:
    get:
      description: |-
        Logout Datas
        <br>
      operationId: AuthController.Logout
      parameters:
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - ""
  /refresh:
    get:
      description: |-
        Refresh Datas
        <br>
      operationId: AuthController.Refresh
      parameters:
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - ""
  /response/{table}:
    delete:
      description: |-
        Delete Datas
        <br>
      operationId: GenericController.Delete
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - response
    get:
      description: |-
        Get Datas
        <br>
      operationId: GenericController.Get
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - response
    post:
      description: |-
        Post Datas
        <br>
      operationId: GenericController.Post
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      - description: 'Request body '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/json'
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - response
    put:
      description: |-
        Put Datas
        <br>
      operationId: GenericController.Put
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      - description: 'Request body '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/json'
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - response
  /response/{table}/{function}:
    get:
      description: |-
        Math Datas
        <br>
      operationId: GenericController.Math
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: Value of the function
        in: path
        name: function
        required: true
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - response
swagger: "2.0"
