basePath: /v1
definitions:
  json:
    title: json
    type: object
info:
  contact:
    email: yves.cerezal@irt-saintexupery.com
  description: |
    Generic database access API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.irt-saintexupery.com/
  title: SqlDB WS API
  version: 1.0.0
paths:
  /auth/login:
    post:
      description: |-
        Login Datas
        <br>
      operationId: AuthController.Login
      parameters:
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      - description: 'Request body '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/json'
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - auth
  /auth/logout:
    get:
      description: |-
        Logout Datas
        <br>
      operationId: AuthController.Logout
      parameters:
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - auth
  /generic/{table}:
    delete:
      description: |-
        Delete Datas
        <br>
      operationId: GenericController.Delete
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: (Optionnal) Value of rows
        in: query
        name: rows
        type: string
      - description: (Optionnal) Value of columns
        in: query
        name: columns
        type: string
      - description: (Optionnal) Value of orderby
        in: query
        name: orderby
        type: string
      - description: (Optionnal) Value of dir
        in: query
        name: dir
        type: string
      - description: (Optionnal) Value of sqlfilter
        in: query
        name: sqlfilter
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - generic
    get:
      description: |-
        Get Datas
        <br>
      operationId: GenericController.Get
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: (Optionnal) Value of rows
        in: query
        name: rows
        type: string
      - description: (Optionnal) Value of columns
        in: query
        name: columns
        type: string
      - description: (Optionnal) Value of orderby
        in: query
        name: orderby
        type: string
      - description: (Optionnal) Value of dir
        in: query
        name: dir
        type: string
      - description: (Optionnal) Value of sqlfilter
        in: query
        name: sqlfilter
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - generic
    post:
      description: |-
        Post Datas
        <br>
      operationId: GenericController.Post
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: (Optionnal) Value of rows
        in: query
        name: rows
        type: string
      - description: (Optionnal) Value of columns
        in: query
        name: columns
        type: string
      - description: (Optionnal) Value of orderby
        in: query
        name: orderby
        type: string
      - description: (Optionnal) Value of dir
        in: query
        name: dir
        type: string
      - description: (Optionnal) Value of sqlfilter
        in: query
        name: sqlfilter
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      - description: 'Request body '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/json'
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - generic
    put:
      description: |-
        Put Datas
        <br>
      operationId: GenericController.Put
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: (Optionnal) Value of rows
        in: query
        name: rows
        type: string
      - description: (Optionnal) Value of columns
        in: query
        name: columns
        type: string
      - description: (Optionnal) Value of orderby
        in: query
        name: orderby
        type: string
      - description: (Optionnal) Value of dir
        in: query
        name: dir
        type: string
      - description: (Optionnal) Value of sqlfilter
        in: query
        name: sqlfilter
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      - description: 'Request body '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/json'
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - generic
  /generic/{table}/{totable}:
    post:
      description: |-
        Link Datas
        <br>
      operationId: GenericController.Link
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: Value of the totable
        in: path
        name: totable
        required: true
        type: string
      - description: (Optionnal) Value of rows
        in: query
        name: rows
        type: string
      - description: (Optionnal) Value of columns
        in: query
        name: columns
        type: string
      - description: (Optionnal) Value of orderby
        in: query
        name: orderby
        type: string
      - description: (Optionnal) Value of dir
        in: query
        name: dir
        type: string
      - description: (Optionnal) Value of sqlfilter
        in: query
        name: sqlfilter
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      - description: 'Request body '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/json'
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - generic
  /generic/{table}/{totable}/delete:
    post:
      description: |-
        UnLink Datas
        <br>
      operationId: GenericController.UnLink
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: Value of the totable
        in: path
        name: totable
        required: true
        type: string
      - description: (Optionnal) Value of rows
        in: query
        name: rows
        type: string
      - description: (Optionnal) Value of columns
        in: query
        name: columns
        type: string
      - description: (Optionnal) Value of orderby
        in: query
        name: orderby
        type: string
      - description: (Optionnal) Value of dir
        in: query
        name: dir
        type: string
      - description: (Optionnal) Value of sqlfilter
        in: query
        name: sqlfilter
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      - description: 'Request body '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/json'
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - generic
  /generic/{table}/import/{filename}:
    delete:
      description: |-
        NotImportated Datas
        <br>
      operationId: GenericController.NotImportated
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: Value of the filename
        in: path
        name: filename
        required: true
        type: string
      - description: (Optionnal) Value of rows
        in: query
        name: rows
        type: string
      - description: (Optionnal) Value of columns
        in: query
        name: columns
        type: string
      - description: (Optionnal) Value of orderby
        in: query
        name: orderby
        type: string
      - description: (Optionnal) Value of dir
        in: query
        name: dir
        type: string
      - description: (Optionnal) Value of sqlfilter
        in: query
        name: sqlfilter
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - generic
    post:
      description: |-
        Importated Datas
        <br>
      operationId: GenericController.Importated
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: Value of the filename
        in: path
        name: filename
        required: true
        type: string
      - description: (Optionnal) Value of rows
        in: query
        name: rows
        type: string
      - description: (Optionnal) Value of columns
        in: query
        name: columns
        type: string
      - description: (Optionnal) Value of orderby
        in: query
        name: orderby
        type: string
      - description: (Optionnal) Value of dir
        in: query
        name: dir
        type: string
      - description: (Optionnal) Value of sqlfilter
        in: query
        name: sqlfilter
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      - description: 'Request body '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/json'
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - generic
swagger: "2.0"
