basePath: /v1
definitions:
  json:
    title: json
    type: object
info:
  contact:
    email: yves.cerezal@irt-saintexupery.com
  description: |
    Generic database access API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.irt-saintexupery.com/
  title: SqlDB WS API
  version: 1.0.0
paths:
  /auth/logcheck:
    get:
      description: |-
        LogCheck Datas
        <br>
      operationId: AuthController.LogCheck
      parameters:
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - auth
  /auth/login:
    post:
      description: |-
        Login Datas
        <br>
      operationId: AuthController.Login
      parameters:
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      - description: 'Request body '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/json'
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - auth
  /auth/logout:
    get:
      description: |-
        Logout Datas
        <br>
      operationId: AuthController.Logout
      parameters:
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - auth
  /generic/{table}:
    delete:
      description: |-
        Delete Datas
        <br>
      operationId: GenericController.Delete
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: needed on a rows level request (value=all for post/put method
          or a get/delete all)
        in: query
        name: rows
        type: string
      - description: needed on a columns level request (POST/PUT/DELETE with no rows
          query params) will set up a view on row level (show only expected columns)
        in: query
        name: columns
        type: string
      - description: sets up a sql order in query (don't even try to inject you little
          joker)
        in: query
        name: orderby
        type: string
      - description: sets up a sql direction in query (ex.ASC|DESC) (don't even try
          to inject you little joker)
        in: query
        name: dir
        type: string
      - description: (Optionnal) Value of limit
        in: query
        name: limit
        type: string
      - description: (Optionnal) Value of offset
        in: query
        name: offset
        type: string
      - description: activate a lightest response (name only)
        in: query
        name: shallow
        type: string
      - description: set 'enable' to activate a response without the main response
          format
        in: query
        name: rawview
        type: string
      - description: (Optionnal) Value of super
        in: query
        name: super
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - generic
    get:
      description: |-
        Get Datas
        <br>
      operationId: GenericController.Get
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: needed on a rows level request (value=all for post/put method
          or a get/delete all)
        in: query
        name: rows
        type: string
      - description: needed on a columns level request (POST/PUT/DELETE with no rows
          query params) will set up a view on row level (show only expected columns)
        in: query
        name: columns
        type: string
      - description: sets up a sql order in query (don't even try to inject you little
          joker)
        in: query
        name: orderby
        type: string
      - description: sets up a sql direction in query (ex.ASC|DESC) (don't even try
          to inject you little joker)
        in: query
        name: dir
        type: string
      - description: (Optionnal) Value of limit
        in: query
        name: limit
        type: string
      - description: (Optionnal) Value of offset
        in: query
        name: offset
        type: string
      - description: activate a lightest response (name only)
        in: query
        name: shallow
        type: string
      - description: set 'enable' to activate a response without the main response
          format
        in: query
        name: rawview
        type: string
      - description: (Optionnal) Value of super
        in: query
        name: super
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - generic
    post:
      description: |-
        Post Datas
        <br>
      operationId: GenericController.Post
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: needed on a rows level request (value=all for post/put method
          or a get/delete all)
        in: query
        name: rows
        type: string
      - description: needed on a columns level request (POST/PUT/DELETE with no rows
          query params) will set up a view on row level (show only expected columns)
        in: query
        name: columns
        type: string
      - description: sets up a sql order in query (don't even try to inject you little
          joker)
        in: query
        name: orderby
        type: string
      - description: sets up a sql direction in query (ex.ASC|DESC) (don't even try
          to inject you little joker)
        in: query
        name: dir
        type: string
      - description: (Optionnal) Value of limit
        in: query
        name: limit
        type: string
      - description: (Optionnal) Value of offset
        in: query
        name: offset
        type: string
      - description: activate a lightest response (name only)
        in: query
        name: shallow
        type: string
      - description: set 'enable' to activate a response without the main response
          format
        in: query
        name: rawview
        type: string
      - description: (Optionnal) Value of super
        in: query
        name: super
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      - description: 'Request body '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/json'
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - generic
    put:
      description: |-
        Put Datas
        <br>
      operationId: GenericController.Put
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: needed on a rows level request (value=all for post/put method
          or a get/delete all)
        in: query
        name: rows
        type: string
      - description: needed on a columns level request (POST/PUT/DELETE with no rows
          query params) will set up a view on row level (show only expected columns)
        in: query
        name: columns
        type: string
      - description: sets up a sql order in query (don't even try to inject you little
          joker)
        in: query
        name: orderby
        type: string
      - description: sets up a sql direction in query (ex.ASC|DESC) (don't even try
          to inject you little joker)
        in: query
        name: dir
        type: string
      - description: (Optionnal) Value of limit
        in: query
        name: limit
        type: string
      - description: (Optionnal) Value of offset
        in: query
        name: offset
        type: string
      - description: activate a lightest response (name only)
        in: query
        name: shallow
        type: string
      - description: set 'enable' to activate a response without the main response
          format
        in: query
        name: rawview
        type: string
      - description: (Optionnal) Value of super
        in: query
        name: super
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      - description: 'Request body '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/json'
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - generic
  /generic/{table}/{filename}/import:
    delete:
      description: |-
        NotImportated Datas
        <br>
      operationId: GenericController.NotImportated
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: Value of the filename
        in: path
        name: filename
        required: true
        type: string
      - description: needed on a rows level request (value=all for post/put method
          or a get/delete all)
        in: query
        name: rows
        type: string
      - description: needed on a columns level request (POST/PUT/DELETE with no rows
          query params) will set up a view on row level (show only expected columns)
        in: query
        name: columns
        type: string
      - description: sets up a sql order in query (don't even try to inject you little
          joker)
        in: query
        name: orderby
        type: string
      - description: sets up a sql direction in query (ex.ASC|DESC) (don't even try
          to inject you little joker)
        in: query
        name: dir
        type: string
      - description: (Optionnal) Value of limit
        in: query
        name: limit
        type: string
      - description: (Optionnal) Value of offset
        in: query
        name: offset
        type: string
      - description: activate a lightest response (name only)
        in: query
        name: shallow
        type: string
      - description: set 'enable' to activate a response without the main response
          format
        in: query
        name: rawview
        type: string
      - description: (Optionnal) Value of super
        in: query
        name: super
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - generic
    post:
      description: |-
        Importated Datas
        <br>
      operationId: GenericController.Importated
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: Value of the filename
        in: path
        name: filename
        required: true
        type: string
      - description: needed on a rows level request (value=all for post/put method
          or a get/delete all)
        in: query
        name: rows
        type: string
      - description: needed on a columns level request (POST/PUT/DELETE with no rows
          query params) will set up a view on row level (show only expected columns)
        in: query
        name: columns
        type: string
      - description: sets up a sql order in query (don't even try to inject you little
          joker)
        in: query
        name: orderby
        type: string
      - description: sets up a sql direction in query (ex.ASC|DESC) (don't even try
          to inject you little joker)
        in: query
        name: dir
        type: string
      - description: (Optionnal) Value of limit
        in: query
        name: limit
        type: string
      - description: (Optionnal) Value of offset
        in: query
        name: offset
        type: string
      - description: activate a lightest response (name only)
        in: query
        name: shallow
        type: string
      - description: set 'enable' to activate a response without the main response
          format
        in: query
        name: rawview
        type: string
      - description: (Optionnal) Value of super
        in: query
        name: super
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      - description: 'Request body '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/json'
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - generic
  /generic/{table}/count:
    get:
      description: |-
        Count Datas
        <br>
      operationId: GenericController.Count
      parameters:
      - description: Value of the table
        in: path
        name: table
        required: true
        type: string
      - description: needed on a rows level request (value=all for post/put method
          or a get/delete all)
        in: query
        name: rows
        type: string
      - description: needed on a columns level request (POST/PUT/DELETE with no rows
          query params) will set up a view on row level (show only expected columns)
        in: query
        name: columns
        type: string
      - description: sets up a sql order in query (don't even try to inject you little
          joker)
        in: query
        name: orderby
        type: string
      - description: sets up a sql direction in query (ex.ASC|DESC) (don't even try
          to inject you little joker)
        in: query
        name: dir
        type: string
      - description: (Optionnal) Value of limit
        in: query
        name: limit
        type: string
      - description: (Optionnal) Value of offset
        in: query
        name: offset
        type: string
      - description: activate a lightest response (name only)
        in: query
        name: shallow
        type: string
      - description: set 'enable' to activate a response without the main response
          format
        in: query
        name: rawview
        type: string
      - description: (Optionnal) Value of super
        in: query
        name: super
        type: string
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - generic
  /main:
    get:
      description: |-
        Main Datas
        <br>
      operationId: MainController.Main
      parameters:
      - description: 'Authorization Token HEADER '
        in: header
        name: Authorization
        type: string
      responses:
        "200":
          description: '{string} success !'
        "403":
          description: no table
      tags:
      - main
swagger: "2.0"
