package entities

var DBRootViews = []map[string]interface{}{ 
	map[string]interface{} { NAMEATTR : "new data entry",
	"is_list" : false,
	"indexable" : true,
	"description" : "select a fom to submit an entry.",
	"readonly" : false,
	"index" : 0,
	"sql_order" : nil,
	"sql_view" : "name,dbworkflow_id",
	"sql_dir" : nil,
	"through_perms" : nil,
	"dbview_id" : nil,
	"link" : DBRequest.Name,
	"is_empty" : true,
	"sql_restriction" : nil, },
	map[string]interface{} { NAMEATTR : "my unvalidated datas",
	"is_list" : true,
	"indexable" : true,
	"description" : nil,
	"readonly" : true,
	"index" : 1,
	"sql_order" : nil,
	"sql_view" : "name,state,dbdest_table_id,dbschema_id",
	"sql_dir" : nil,
	"through_perms" : nil,
	"dbview_id" : nil,
	"link" : DBRequest.Name,
	"is_empty" : false,
	"sql_restriction" : "state!='completed'", },
	map[string]interface{} { NAMEATTR : "my validated datas",
	"is_list" : true,
	"indexable" : true,
	"description" : nil,
	"readonly" : true,
	"index" : 1,
	"sql_order" : nil,
	"sql_view" : "name,dbdest_table_id,dbschema_id",
	"sql_dir" : nil,
	"through_perms" : nil,
	"dbview_id" : nil,
	"link" : DBRequest.Name,
	"is_empty" : false,
	"sql_restriction" : "state='completed'", },
	map[string]interface{} { NAMEATTR : "assigned activity",
	"is_list" : true,
	"indexable" : true,
	"description" : nil,
	"readonly" : false,
	"index" : 1,
	"sql_order" : nil,
	"sql_view" : "name,state,description,urgency,priority, dbcreated_by_id",
	"sql_dir" : nil,
	"through_perms" : nil,
	"dbview_id" : nil,
	"link" : DBTask.Name,
	"is_empty" : false,
	"sql_restriction" : "is_close=false", },
	map[string]interface{} { NAMEATTR : "archived activity",
	"is_list" : true,
	"indexable" : true,
	"description" : nil,
	"readonly" : true,
	"index" : 1,
	"sql_order" : nil,
	"sql_view" : "name,description,urgency,priority, dbcreated_by_id",
	"sql_dir" : nil,
	"through_perms" : nil,
	"dbview_id" : nil,
	"link" : DBTask.Name,
	"is_empty" : false,
	"sql_restriction" : "is_close=true",},
}
var DBRootWorkflows = []map[string]interface{}{ 
	map[string]interface{}{
		NAMEATTR: "create a view",
		"description": "new view workflow",
		"link": DBView.Name,
	}, 
	map[string]interface{}{
		NAMEATTR: "create a template",
		"description": "new template workflow",
		"link": DBSchema.Name,
	}, 
	map[string]interface{}{
		NAMEATTR: "create a template field",
		"description": "new template field workflow",
		"link": DBSchemaField.Name,
	}, 
	map[string]interface{}{
		NAMEATTR: "create a user",
		"description": "new user workflow",
		"link": DBUser.Name,
	}, 
	map[string]interface{}{
		NAMEATTR: "create an entity",
		"description": "new entity workflow",
		"link": DBUser.Name,
	}, 
	map[string]interface{}{
		NAMEATTR: "create a role",
		"description": "new role workflow",
		"link": DBRole.Name,
	}, 
	map[string]interface{}{
		NAMEATTR: "create a permission",
		"description": "new permission workflow",
		"link": DBPermission.Name,
	}, 
	map[string]interface{}{
		NAMEATTR: "bind a permission to a role",
		"description": "new permission affectation to a role workflow",
		"link": DBRolePermission.Name,
	}, 
	map[string]interface{}{
		NAMEATTR: "bind a role to a user/entity",
		"description": "new role attribution workflow",
		"link": DBRoleAttribution.Name,
	}, 
	map[string]interface{}{
		NAMEATTR: "bind a user to an entity",
		"description": "new user attribution to an entity workflow",
		"link": DBEntityUser.Name,
	},
	map[string]interface{}{
		NAMEATTR: "create a workflow",
		"description": "new workflow workflow",
		"link": DBWorkflow.Name,
	}, 
}