version: '3.1'

services:

  pg:
    image: postgres:alpine
    restart: always
    volumes:
      - ./autoload:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080